"""
자동 FAQ 생성 서비스

사용자 질문 로그를 분석하여 자동으로 FAQ 후보를 선정하고 초안을 생성합니다.

흐름:
1. 백엔드 /api/ai-logs API 호출하여 질문 로그 가져오기
2. 유사 질문 클러스터링 (rapidfuzz 사용)
3. 빈도 높은 클러스터를 FAQ 후보로 선정
4. autoGenerateDrafts=true면 기존 FaqDraftService로 초안 생성
"""

import hashlib
import uuid
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

import httpx
from rapidfuzz import fuzz

from app.core.config import get_settings
from app.core.logging import get_logger
from app.models.faq import (
    AutoFaqGenerateRequest,
    AutoFaqGenerateResponse,
    FaqCandidateInfo,
    FaqDraft,
    FaqDraftGenerateRequest,
)
from app.services.faq_service import FaqDraftService, FaqGenerationError

logger = get_logger(__name__)


class FaqAutoService:
    """자동 FAQ 생성 서비스"""

    # 클러스터링 임계값 (유사도 기준)
    CLUSTER_SIMILARITY_THRESHOLD = 80  # 80% 이상 유사하면 같은 클러스터

    def __init__(self, faq_draft_service: Optional[FaqDraftService] = None):
        self.settings = get_settings()
        self.faq_draft_service = faq_draft_service or FaqDraftService()

    async def generate_auto(
        self, request: AutoFaqGenerateRequest
    ) -> AutoFaqGenerateResponse:
        """
        자동 FAQ 생성 파이프라인 실행

        1. 백엔드에서 질문 로그 가져오기
        2. 질문 클러스터링
        3. FAQ 후보 선정
        4. (선택) FAQ 초안 생성
        """
        try:
            # 파라미터 기본값 설정
            domain = request.domain
            min_frequency = request.minFrequency or 3
            max_candidates = request.maxCandidates or 20
            auto_generate_drafts = request.autoGenerateDrafts if request.autoGenerateDrafts is not None else True

            logger.info(
                f"[FAQ Auto] 자동 FAQ 생성 시작: domain={domain}, "
                f"min_frequency={min_frequency}, max_candidates={max_candidates}, "
                f"auto_generate_drafts={auto_generate_drafts}"
            )

            # 1. 백엔드에서 질문 로그 가져오기
            question_logs = await self._fetch_question_logs(domain)
            if not question_logs:
                logger.warning("[FAQ Auto] 질문 로그가 없습니다.")
                return AutoFaqGenerateResponse(
                    status="FAILED",
                    candidates_found=0,
                    drafts_generated=0,
                    drafts_failed=0,
                    candidates=[],
                    drafts=[],
                    error_message="질문 로그가 없습니다."
                )

            logger.info(f"[FAQ Auto] 질문 로그 {len(question_logs)}개 조회됨")

            # 2. 질문 클러스터링
            clusters = self._cluster_questions(question_logs)
            logger.info(f"[FAQ Auto] 클러스터 {len(clusters)}개 생성됨")

            # 3. 빈도 기반 후보 선정 (min_frequency 이상)
            candidates = self._select_candidates(
                clusters, min_frequency, max_candidates
            )
            logger.info(f"[FAQ Auto] FAQ 후보 {len(candidates)}개 선정됨")

            if not candidates:
                return AutoFaqGenerateResponse(
                    status="SUCCESS",
                    candidates_found=0,
                    drafts_generated=0,
                    drafts_failed=0,
                    candidates=[],
                    drafts=[],
                    error_message=None
                )

            # 4. (선택) FAQ 초안 생성
            drafts: List[FaqDraft] = []
            drafts_failed = 0

            if auto_generate_drafts:
                for candidate in candidates:
                    try:
                        draft = await self._generate_draft_for_candidate(candidate, domain)
                        if draft:
                            drafts.append(draft)
                    except Exception as e:
                        logger.warning(
                            f"[FAQ Auto] FAQ 초안 생성 실패: cluster_id={candidate.cluster_id}, error={e}"
                        )
                        drafts_failed += 1

            # 결과 상태 결정
            if drafts_failed == 0 and len(drafts) == len(candidates):
                status = "SUCCESS"
            elif len(drafts) > 0:
                status = "PARTIAL"
            elif not auto_generate_drafts:
                status = "SUCCESS"  # 초안 생성 안함
            else:
                status = "FAILED"

            logger.info(
                f"[FAQ Auto] 자동 FAQ 생성 완료: status={status}, "
                f"candidates={len(candidates)}, drafts={len(drafts)}, failed={drafts_failed}"
            )

            return AutoFaqGenerateResponse(
                status=status,
                candidates_found=len(candidates),
                drafts_generated=len(drafts),
                drafts_failed=drafts_failed,
                candidates=candidates,
                drafts=drafts,
                error_message=None
            )

        except Exception as e:
            logger.exception(f"[FAQ Auto] 자동 FAQ 생성 실패: {e}")
            return AutoFaqGenerateResponse(
                status="FAILED",
                candidates_found=0,
                drafts_generated=0,
                drafts_failed=0,
                candidates=[],
                drafts=[],
                error_message=f"자동 FAQ 생성 실패: {str(e)}"
            )

    async def _fetch_question_logs(
        self, domain: Optional[str] = None
    ) -> List[Dict[str, str]]:
        """
        백엔드 /api/ai-logs API 호출하여 질문 로그 가져오기

        Returns:
            질문 로그 리스트: [{"domain": "...", "intent": "...", "question_masked": "..."}]
        """
        try:
            backend_url = self.settings.BACKEND_BASE_URL
            if not backend_url:
                logger.warning("[FAQ Auto] BACKEND_BASE_URL이 설정되지 않았습니다.")
                return []

            # infra-service는 9003 포트, 하지만 gateway를 통해 접근
            # /api/ai-logs는 infra-service의 엔드포인트
            url = f"{backend_url}/api/ai-logs"
            params = {"limit": 500}

            headers = {}
            if self.settings.BACKEND_API_TOKEN:
                headers["Authorization"] = f"Bearer {self.settings.BACKEND_API_TOKEN}"

            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.get(url, params=params, headers=headers)

            if response.status_code != 200:
                logger.warning(
                    f"[FAQ Auto] 질문 로그 조회 실패: status={response.status_code}"
                )
                return []

            data = response.json()
            logs = data.get("logs", [])

            # 도메인 필터링
            if domain:
                logs = [log for log in logs if log.get("domain") == domain]

            return logs

        except Exception as e:
            logger.warning(f"[FAQ Auto] 질문 로그 조회 중 오류: {e}")
            return []

    def _cluster_questions(
        self, logs: List[Dict[str, str]]
    ) -> Dict[str, List[Dict[str, str]]]:
        """
        유사 질문 클러스터링 (rapidfuzz 사용)

        Returns:
            클러스터 딕셔너리: {cluster_id: [로그 리스트]}
        """
        clusters: Dict[str, List[Dict[str, str]]] = {}
        cluster_representatives: Dict[str, str] = {}  # cluster_id -> 대표 질문

        for log in logs:
            question = log.get("question_masked", "").strip()
            if not question or len(question) < 5:
                continue

            # 기존 클러스터와 비교
            matched_cluster_id = None
            for cluster_id, representative in cluster_representatives.items():
                similarity = fuzz.ratio(question.lower(), representative.lower())
                if similarity >= self.CLUSTER_SIMILARITY_THRESHOLD:
                    matched_cluster_id = cluster_id
                    break

            if matched_cluster_id:
                clusters[matched_cluster_id].append(log)
            else:
                # 새 클러스터 생성
                cluster_id = self._generate_cluster_id(question)
                clusters[cluster_id] = [log]
                cluster_representatives[cluster_id] = question

        return clusters

    def _generate_cluster_id(self, question: str) -> str:
        """질문 기반 클러스터 ID 생성"""
        hash_str = hashlib.md5(question.encode()).hexdigest()[:8]
        return f"cluster-{hash_str}"

    def _select_candidates(
        self,
        clusters: Dict[str, List[Dict[str, str]]],
        min_frequency: int,
        max_candidates: int
    ) -> List[FaqCandidateInfo]:
        """
        빈도 기반 FAQ 후보 선정

        Args:
            clusters: 클러스터 딕셔너리
            min_frequency: 최소 빈도
            max_candidates: 최대 후보 수

        Returns:
            FAQ 후보 리스트
        """
        candidates = []

        # 빈도 순으로 정렬
        sorted_clusters = sorted(
            clusters.items(),
            key=lambda x: len(x[1]),
            reverse=True
        )

        for cluster_id, logs in sorted_clusters:
            frequency = len(logs)
            if frequency < min_frequency:
                continue

            # 대표 질문 선정 (첫 번째 질문)
            canonical_question = logs[0].get("question_masked", "")

            # 샘플 질문들 (최대 5개)
            sample_questions = list(set(
                log.get("question_masked", "")
                for log in logs[:5]
                if log.get("question_masked")
            ))

            # 점수 계산
            frequency_score = frequency / len(clusters) if clusters else 0
            total_score = frequency_score

            candidate = FaqCandidateInfo(
                candidate_id=f"cand-{uuid.uuid4().hex[:8]}",
                cluster_id=cluster_id,
                canonical_question=canonical_question,
                sample_questions=sample_questions,
                frequency_score=round(frequency_score, 3),
                recency_score=None,  # 추후 구현
                total_score=round(total_score, 3)
            )
            candidates.append(candidate)

            if len(candidates) >= max_candidates:
                break

        return candidates

    async def _generate_draft_for_candidate(
        self,
        candidate: FaqCandidateInfo,
        domain: Optional[str]
    ) -> Optional[FaqDraft]:
        """
        후보에 대한 FAQ 초안 생성

        기존 FaqDraftService.generate_faq_draft 재사용
        """
        try:
            # FaqDraftGenerateRequest 생성
            request = FaqDraftGenerateRequest(
                domain=domain or "GENERAL",
                cluster_id=candidate.cluster_id,
                canonical_question=candidate.canonical_question,
                sample_questions=candidate.sample_questions,
                top_docs=[],  # RAG에서 검색
                avg_intent_confidence=None
            )

            draft = await self.faq_draft_service.generate_faq_draft(request)
            return draft

        except FaqGenerationError as e:
            logger.warning(f"[FAQ Auto] FAQ 초안 생성 실패: {e}")
            return None
        except Exception as e:
            logger.exception(f"[FAQ Auto] FAQ 초안 생성 중 예외: {e}")
            return None


# 싱글턴 인스턴스
_faq_auto_service: Optional[FaqAutoService] = None


def get_faq_auto_service() -> FaqAutoService:
    """FaqAutoService 인스턴스 반환 (싱글턴)"""
    global _faq_auto_service
    if _faq_auto_service is None:
        _faq_auto_service = FaqAutoService()
    return _faq_auto_service
