"""
FAQ 후보 모델 (FAQ Candidate Models)

사용자 질문 로그를 기반으로 FAQ 후보를 생성하는 과정에서 사용되는 모델들입니다.

주요 모델:
- QuestionLog: 사용자 질문 로그
- QuestionCluster: 유사 질문 클러스터
- FaqCandidate: FAQ 후보
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from app.models.faq import FaqDraft


class QuestionLog(BaseModel):
    """
    사용자 질문 로그 모델.
    
    백엔드에서 조회한 질문 로그를 나타냅니다.
    """
    
    log_id: str = Field(..., description="로그 ID")
    question_masked: str = Field(..., description="마스킹된 질문 텍스트")
    domain: str = Field(..., description="도메인 (POLICY, EDUCATION 등)")
    intent: str = Field(..., description="의도 (POLICY_QA 등)")
    created_at: datetime = Field(..., description="생성 시각")
    user_id: Optional[str] = Field(None, description="사용자 ID")
    session_id: Optional[str] = Field(None, description="세션 ID")
    count: int = Field(default=1, description="동일 질문 빈도 (집계된 경우)")


class QuestionCluster(BaseModel):
    """
    유사 질문 클러스터 모델.
    
    유사한 의미의 질문들을 그룹화한 클러스터입니다.
    """
    
    cluster_id: str = Field(..., description="클러스터 ID")
    canonical_question: str = Field(..., description="대표 질문")
    sample_questions: List[str] = Field(..., description="샘플 질문들")
    question_logs: List[QuestionLog] = Field(..., description="포함된 질문 로그들")
    total_count: int = Field(..., description="총 질문 수")
    domain: str = Field(..., description="도메인")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="생성 시각")


class FaqCandidate(BaseModel):
    """
    FAQ 후보 모델.
    
    자주 묻는 질문으로 선정된 후보입니다.
    """
    
    candidate_id: str = Field(..., description="후보 ID")
    cluster: QuestionCluster = Field(..., description="질문 클러스터")
    frequency_score: float = Field(..., description="빈도 점수 (0~1)")
    recency_score: float = Field(..., description="최근성 점수 (0~1)")
    total_score: float = Field(..., description="종합 점수 (0~1)")
    selected_at: datetime = Field(default_factory=datetime.utcnow, description="선정 시각")


class FaqCandidateListResponse(BaseModel):
    """
    FAQ 후보 목록 응답 모델.
    """
    
    candidates: List[FaqCandidate] = Field(..., description="FAQ 후보 목록")
    total_count: int = Field(..., description="전체 후보 수")
    domain: Optional[str] = Field(None, description="도메인 필터 (있으면)")


class AutoFaqGenerateRequest(BaseModel):
    """
    자동 FAQ 생성 요청 모델.
    
    사용자 질문 로그를 기반으로 자동으로 FAQ를 생성합니다.
    백엔드에서 camelCase JSON으로 전송됩니다.
    """
    
    model_config = ConfigDict(
        populate_by_name=True,  # 필드명과 alias 모두로 값 설정 가능
    )
    
    domain: Optional[str] = Field(
        None, 
        description="도메인 필터 (선택)",
        serialization_alias="domain",
    )
    min_frequency: int = Field(
        default=3, 
        description="최소 질문 빈도 (기본 3회)",
        serialization_alias="minFrequency",
    )
    days_back: int = Field(
        default=30, 
        description="조회 기간 (일, 기본 30일)",
        serialization_alias="daysBack",
    )
    max_candidates: int = Field(
        default=20, 
        description="최대 후보 수 (기본 20개)",
        serialization_alias="maxCandidates",
    )
    auto_generate_drafts: bool = Field(
        default=True, 
        description="자동으로 FAQ 초안 생성 여부",
        serialization_alias="autoGenerateDrafts",
    )


class AutoFaqGenerateResponse(BaseModel):
    """
    자동 FAQ 생성 응답 모델.
    """
    
    status: str = Field(..., description="처리 상태 (SUCCESS, PARTIAL, FAILED)")
    candidates_found: int = Field(..., description="발견된 후보 수")
    drafts_generated: int = Field(..., description="생성된 초안 수")
    drafts_failed: int = Field(..., description="실패한 초안 수")
    candidates: List[FaqCandidate] = Field(default_factory=list, description="FAQ 후보 목록")
    drafts: List[FaqDraft] = Field(default_factory=list, description="생성된 FAQ 초안 목록")
    error_message: Optional[str] = Field(None, description="에러 메시지 (실패 시)")

