name: AI Server Deploy

on:
  push:
    branches: ["main"] # 메인 브랜치에 코드가 푸시되면 실행

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and Run AI Code
        run: |
          cd /home/team4/ctrlf-ai || exit
          
          git fetch origin
          git reset --hard origin/main

          docker compose --profile real down || true
          
          docker compose --profile real up --build -d

          echo "Deployment successful."
          docker compose --profile real ps
